### PR TITLE
Missing compiled metadata

### LINKED ISSUE #453: Include metadata for compiled qiskit circuit
### What is happening?

When I use cq_compile on a qiskit QuantumCircuit that has metadata stored in circuit.metadata, the compiled circuit does not carry over that metadata.

### What are the current alternatives?

I work around this inconvenience by keeping the original circuit around and accessing its metadata later, or I just set the compiled circuit's metadata to be equal to that of the original.

### Any additional context?

image

### PR DESCRIPTION
**Pull request by bharat-thotakura**
Fixes #453

### CODE REVIEW

**Review by dowusu-antwi — CHANGES_REQUESTED** [review]
Nice. We should also do this for `ibmq_compile`, `aqt_compile`, etc.:
image

**Review by dowusu-antwi — COMMENTED** [review]
Additionally, error message is fixed after updating branch / merging.

**Comment by bharat-thotakura** [comment]
> Nice. We should also do this for `ibmq_compile`, `aqt_compile`, etc.: image

Should work for those too now with 113d45f

**Review by dowusu-antwi — APPROVED** [review]
Great, lgtm!

**Pull request merged**
