### PR TITLE
Add qscout_tutorial.ipynb to qiskit-superstaq/examples

### PR DESCRIPTION
**Pull request by vtomole**
Moving https://github.com/SupertechLabs/qiskit-superstaq/pull/317

### CODE REVIEW

**Comment by stephanielee9** [comment]
@hallben4 Could you address comments on this PR? Reach out to @richrines1 if you have questions!

**Comment by hallben4** [comment]
When I comment out the line:
! pip install pylatexenc
As suggested by @richrines1 , the "notebook check" check doesn't pass and gives:
"The 'pylatexenc' library is required to use 'MatplotlibDrawer'. You can install it with 'pip install pylatexenc'."

How can this be resolved?

**Comment by stephanielee9** [comment]
@hallben4 I had to do the same for https://github.com/SupertechLabs/client-superstaq/pull/428. See https://github.com/SupertechLabs/client-superstaq/pull/428/commits/15c4094a5a5546a2a9ceb2e9950aee0999456f1f and https://github.com/SupertechLabs/client-superstaq/pull/428/commits/6189c3fa12d53e3c1da7697cb150cb27d2d8361d

**Review by richrines1 — APPROVED** [review]
lgtm!

**Review by bharat-thotakura — APPROVED** [review]

**Pull request merged**
