### PR TITLE
loosen qiskit requirement

### PR DESCRIPTION
**Pull request by richrines1**
* updates qiskit-superstaq to support newer qiskit versions (no longer pinned to those with terra version 0.23.*)
* updates cirq-superstaq[examples] to require terra 0.24.* instead of 0.23.*

### CODE REVIEW

**Review by vtomole — APPROVED** [review]
LGTM

**Review by dowusu-antwi — APPROVED** [review]
Can you test this with one of the `cirq-superstaq` notebooks that use `qiskit`? Otherwise LGTM too.

**Review by bharat-thotakura — APPROVED** [review]
LGTM

**Comment by vtomole** [comment]
> Can you test this with one of the cirq-superstaq notebooks that use qiskit

Theoretically the notebook checks should do this job for us already.

**Comment by dowusu-antwi** [comment]
> Theoretically the notebook checks should do this job for us already.


Gp. The notebook checks do `cirq-superstaq/docs/ibm_cirq_superstaq.ipynb` -- but I wondered specifically about `docs/source/optimizations/ibm/ibmq_compile_css.ipynb`

**Comment by richrines1** [comment]
> but I wondered specifically about `docs/source/optimizations/ibm/ibmq_compile_css.ipynb`

just confirmed it does run after installing cirq-superstaq[dev]/[examples]. I also updated the qiskit versions used in the check at the top of the notebook (and removed an equivalent check in css/examples/resource_estimate.ipynb), but that said this check is still broken - it will install the most recent version (via `cirq-superstaq[examples]`), but it won't be reloaded so the notebook will still fail.. so we should definitely rethink how we do this more generally

**Pull request merged**
